WITH full_sample AS (
  SELECT address,
         stamps,
         ROW_NUMBER() OVER (ORDER BY 2) AS row_num
  FROM passport.human_stamps
  WHERE array_length(stamps, 1) >= 6
), sample1 as (
            SELECT address, stamps as stamp_array
               FROM (SELECT address, stamps,
                            row_num % 2 AS remainder
                     FROM full_sample) s
               WHERE remainder = 0 --sample1
), sample2 as (
            SELECT address, stamps as stamp_array
               FROM (SELECT address, stamps,
                            row_num % 2 AS remainder
                     FROM full_sample) s
               WHERE remainder = 1
)
select address,
  CASE WHEN 'Brightid' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Brightid,
  CASE WHEN 'Coinbase' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Coinbase,
  CASE WHEN 'CommunityStakingBronze' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS CommunityStakingBronze,
  CASE WHEN 'CommunityStakingSilver' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS CommunityStakingSilver,
  CASE WHEN 'CommunityStakingGold' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS CommunityStakingGold,
  CASE WHEN 'Discord' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Discord,
  CASE WHEN 'Ens' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Ens,
  CASE WHEN 'EthGasProvider' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS EthGasProvider,
  CASE WHEN 'EthGTEOneTxnProvider' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS EthGTEOneTxnProvider,
  CASE WHEN 'ethPossessionsGte#1' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS ethPossessionsGte#1,
  CASE WHEN 'ethPossessionsGte#10' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS ethPossessionsGte#10,
  CASE WHEN 'ethPossessionsGte#32' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS ethPossessionsGte#32,
  CASE WHEN 'Facebook' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Facebook,
  CASE WHEN 'FacebookProfilePicture' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS FacebookProfilePicture,
  CASE WHEN 'FiftyOrMoreGithubFollowers' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS FiftyOrMoreGithubFollowers,
  CASE WHEN 'FirstEthTxnProvider' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS FirstEthTxnProvider,
  CASE WHEN 'FiveOrMoreGithubRepos' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS FiveOrMoreGithubRepos,
  CASE WHEN 'ForkedGithubRepoProvider' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS ForkedGithubRepoProvider,
  CASE WHEN 'GitcoinContributorStatistics#numGr14ContributionsGte#1' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinContributorStatistics1,
  CASE WHEN 'GitcoinContributorStatistics#numGrantsContributeToGte#1' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinContributorStatisticsGrants1,
  CASE WHEN 'GitcoinContributorStatistics#numGrantsContributeToGte#10' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinContributorStatisticsGrants10,
  CASE WHEN 'GitcoinContributorStatistics#numGrantsContributeToGte#100' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinContributorStatisticsGrants100,
  CASE WHEN 'GitcoinContributorStatistics#numGrantsContributeToGte#25' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinContributorStatisticsGrants25,
  CASE WHEN 'GitcoinContributorStatistics#numRoundsContributedToGte#1' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinContributorStatisticsRounds1,
  CASE WHEN 'GitcoinContributorStatistics#totalContributionAmountGte#10' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinContributorStatisticsAmtG10,
  CASE WHEN 'GitcoinContributorStatistics#totalContributionAmountGte#100' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinContributorStatisticsAmtG100,
  CASE WHEN 'GitcoinContributorStatistics#totalContributionAmountGte#1000' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinContributorStatisticsAmtG1000,
  CASE WHEN 'GitcoinGranteeStatistics#numGrantContributors#10' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinGranteeStatisticsContr10,
  CASE WHEN 'GitcoinGranteeStatistics#numGrantContributors#100' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinGranteeStatisticsContr100,
  CASE WHEN 'GitcoinGranteeStatistics#numGrantContributors#25' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinGranteeStatisticsContr25,
  CASE WHEN 'GitcoinGranteeStatistics#numGrantsInEcoAndCauseRound#1' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinGranteeStatisticsCause1,
  CASE WHEN 'GitcoinGranteeStatistics#numOwnedGrants#1' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinGranteeStatisticsOwned1,
  CASE WHEN 'GitcoinGranteeStatistics#totalContributionAmount#100' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinGranteeStatisticsAmt100,
  CASE WHEN 'GitcoinGranteeStatistics#totalContributionAmount#1000' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinGranteeStatisticsContr1000,
  CASE WHEN 'GitcoinGranteeStatistics#totalContributionAmount#10000' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitcoinGranteeStatisticsContr10000,
  CASE WHEN 'Github' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Github,
  CASE WHEN 'GitPOAP' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GitPoap,
  CASE WHEN 'GnosisSafe' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GnosisSafe,
  CASE WHEN 'Google' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Google,
  CASE WHEN 'gtcPossessionsGte#100' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS gtcPossessionsGte100,
  CASE WHEN 'GuildAdmin' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GuildAdmin,
  CASE WHEN 'GuildMember' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GuildMember,
  CASE WHEN 'GuildPassportMember' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS GuildPassportMember,
  CASE WHEN 'HolonymGovIdProvider' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS HolonymGovIdProvider,
  CASE WHEN 'Hypercerts' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Hypercerts,
  CASE WHEN 'IdenaAge#10' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS IdenaAge10,
  CASE WHEN 'IdenaAge#5' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS IdenaAge5,
  CASE WHEN 'IdenaStake#100k' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS IdenaStake100k,
  CASE WHEN 'IdenaStake#10k' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS IdenaStake10k,
  CASE WHEN 'IdenaStake#1k' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS IdenaStake1k,
  CASE WHEN 'IdenaState#Human' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS IdenaStateHuman,
  CASE WHEN 'IdenaState#Newbie' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS IdenaStateNewbie,
  CASE WHEN 'IdenaState#Verified' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS IdenaStateVerified,
  CASE WHEN 'Lens' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Lens,
  CASE WHEN 'Linkedin' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Linkedin,
  CASE WHEN 'NFT' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Nft,
  CASE WHEN 'PHIActivityGold' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS PHIActivityGold,
  CASE WHEN 'PHIActivitySilver' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS PHIActivitySilver,
  CASE WHEN 'POAP' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS POAP,
  CASE WHEN 'Poh' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Poh,
  CASE WHEN 'SelfStakingBronze' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS SelfStakingBronze,
  CASE WHEN 'SelfStakingGold' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS SelfStakingGold,
  CASE WHEN 'SelfStakingSilver' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS SelfStakingSilver,
  CASE WHEN 'SnapshotProposalsProvider' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS SnapshotProposalsProvider,
  CASE WHEN 'SnapshotVotesProvider' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS SnapshotVotesProvider,
  CASE WHEN 'StarredGithubRepoProvider' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS StarredGithubRepoProvider,
  CASE WHEN 'TenOrMoreGithubFollowers' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS TenOrMoreGithubFollowers,
  CASE WHEN 'Twitter' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS Twitter,
  CASE WHEN 'TwitterFollowerGT100' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS TwitterFollowerGT100,
  CASE WHEN 'TwitterFollowerGT500' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS TwitterFollowerGT500,
  CASE WHEN 'TwitterFollowerGT5000' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS TwitterFollowerGT5000,
  CASE WHEN 'TwitterFollowerGTE1000' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS TwitterFollowerGTE1000,
  CASE WHEN 'TwitterTweetGT10' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS TwitterTweetGT10,
  CASE WHEN 'ZkSync' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS ZkSync,
  CASE WHEN 'ZkSyncEra' = ANY (stamp_array) THEN TRUE ELSE FALSE END AS ZkSyncEra
from sample1
